name: update-manifest

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update echo message
        run: |
          sed -i 's/hello-from-argo/hello-from-ci/g' k8s/app.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/app.yaml
          git commit -m "ci: update echo message"
          git push
